version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: max_bot_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maxbot -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build: .
    container_name: max_bot
    environment:
      MAX_BOT_TOKEN: ${MAX_BOT_TOKEN}
      POSTGRES_HOST: ${POSTGRES_HOST:-178.72.139.15}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER:-maxbot}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-maxbot123}
      POSTGRES_DB: ${POSTGRES_DB:-maxbot_db}
    volumes:
      - .:/app
    restart: unless-stopped


volumes:
  postgres_data:


